name: Deploy Serverless function
on:
  pull_request:
  #push:
  #  branches:
  #    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: goodsmileduck/yandex-serverless-action@v2
      with:
        token: ${{ secrets.YC_TOKEN }}
        function_id: 'd4e97t2k0851vlo48s7f'
        runtime: 'python39'
        memory: '128'
        entrypoint: 'index.handler'
        environment: BOT_TOKEN=${{ secrets.BOT_TOKEN }}
        source: '.'